// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Calendar struct {
	Path      string
	SyncToken sql.NullString
	Homeset   sql.NullString
}

type EventObject struct {
	Path         string
	CalendarPath string
	Dto          []byte
}

type Metadata struct {
	ID      int64
	Version int64
}
