// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Calendar struct {
	Path      string
	SyncToken sql.NullString
}

type EventObject struct {
	Path         string
	CalendarPath string
	Dto          []byte
	MinStart     time.Time
	MaxEnd       time.Time
}

type Metadata struct {
	ID      int64
	Version int64
}
