// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteAllInPrincipalExcept = `-- name: DeleteAllInPrincipalExcept :exec
delete from calendar
where homeset = ? and path not in (/*SLICE:paths*/?)
`

type DeleteAllInPrincipalExceptParams struct {
	Homeset sql.NullString
	Paths   []string
}

func (q *Queries) DeleteAllInPrincipalExcept(ctx context.Context, arg DeleteAllInPrincipalExceptParams) error {
	query := deleteAllInPrincipalExcept
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Homeset)
	if len(arg.Paths) > 0 {
		for _, v := range arg.Paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(arg.Paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteEvents = `-- name: DeleteEvents :exec
delete from event_object
where path in (/*SLICE:paths*/?)
`

func (q *Queries) DeleteEvents(ctx context.Context, paths []string) error {
	query := deleteEvents
	var queryParams []interface{}
	if len(paths) > 0 {
		for _, v := range paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const putCalendar = `-- name: PutCalendar :exec
insert into calendar (path, sync_token, homeset)
values (?, ?, ?)
on conflict (path) do update set
	sync_token = excluded.sync_token,
	homeset = excluded.homeset
`

type PutCalendarParams struct {
	Path      string
	SyncToken sql.NullString
	Homeset   sql.NullString
}

func (q *Queries) PutCalendar(ctx context.Context, arg PutCalendarParams) error {
	_, err := q.db.ExecContext(ctx, putCalendar, arg.Path, arg.SyncToken, arg.Homeset)
	return err
}

const putEvent = `-- name: PutEvent :exec
insert into event_object (path, calendar_path, dto)
values (?, ?, ?)
on conflict (path) do update set
	calendar_path = excluded.calendar_path,
	dto = excluded.dto
`

type PutEventParams struct {
	Path         string
	CalendarPath string
	Dto          []byte
}

func (q *Queries) PutEvent(ctx context.Context, arg PutEventParams) error {
	_, err := q.db.ExecContext(ctx, putEvent, arg.Path, arg.CalendarPath, arg.Dto)
	return err
}

const putMetadata = `-- name: PutMetadata :exec
insert into metadata (id, version)
values (1, ?)
on conflict (id) do update set
	version = excluded.version
`

func (q *Queries) PutMetadata(ctx context.Context, version int64) error {
	_, err := q.db.ExecContext(ctx, putMetadata, version)
	return err
}

const readCalendar = `-- name: ReadCalendar :one
select sync_token, homeset from calendar where path = ?
`

type ReadCalendarRow struct {
	SyncToken sql.NullString
	Homeset   sql.NullString
}

func (q *Queries) ReadCalendar(ctx context.Context, path string) (ReadCalendarRow, error) {
	row := q.db.QueryRowContext(ctx, readCalendar, path)
	var i ReadCalendarRow
	err := row.Scan(&i.SyncToken, &i.Homeset)
	return i, err
}

const readMetadata = `-- name: ReadMetadata :one
select version from metadata
where id = 1
`

func (q *Queries) ReadMetadata(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, readMetadata)
	var version int64
	err := row.Scan(&version)
	return version, err
}
