// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const deleteEvents = `-- name: DeleteEvents :exec

delete from event_object
where path in (/*SLICE:paths*/?)
`

// implemented manually for perf reasons
// -- name: ReadEvents :many
// select path, dto from event_object where calendar_path = ?;
func (q *Queries) DeleteEvents(ctx context.Context, paths []string) error {
	query := deleteEvents
	var queryParams []interface{}
	if len(paths) > 0 {
		for _, v := range paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const putCalendar = `-- name: PutCalendar :exec
insert into calendar (path, dto, sync_token)
values (?, ?, ?)
on conflict (path) do update set
	dto = excluded.dto,
	sync_token = excluded.sync_token
`

type PutCalendarParams struct {
	Path      string
	Dto       []byte
	SyncToken sql.NullString
}

func (q *Queries) PutCalendar(ctx context.Context, arg PutCalendarParams) error {
	_, err := q.db.ExecContext(ctx, putCalendar, arg.Path, arg.Dto, arg.SyncToken)
	return err
}

const putEvent = `-- name: PutEvent :exec
insert into event_object (path, calendar_path, dto)
values (?, ?, ?)
on conflict (path) do update set
	calendar_path = excluded.calendar_path,
	dto = excluded.dto
`

type PutEventParams struct {
	Path         string
	CalendarPath string
	Dto          []byte
}

func (q *Queries) PutEvent(ctx context.Context, arg PutEventParams) error {
	_, err := q.db.ExecContext(ctx, putEvent, arg.Path, arg.CalendarPath, arg.Dto)
	return err
}

const putMetadata = `-- name: PutMetadata :exec
insert into metadata (id, version)
values (1, ?)
on conflict (id) do update set
	version = excluded.version
`

func (q *Queries) PutMetadata(ctx context.Context, version int64) error {
	_, err := q.db.ExecContext(ctx, putMetadata, version)
	return err
}

const readCalendarDto = `-- name: ReadCalendarDto :one
select dto from calendar where path = ?
`

func (q *Queries) ReadCalendarDto(ctx context.Context, path string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, readCalendarDto, path)
	var dto []byte
	err := row.Scan(&dto)
	return dto, err
}

const readCalendarSyncToken = `-- name: ReadCalendarSyncToken :one
select sync_token from calendar where path = ?
`

func (q *Queries) ReadCalendarSyncToken(ctx context.Context, path string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, readCalendarSyncToken, path)
	var sync_token sql.NullString
	err := row.Scan(&sync_token)
	return sync_token, err
}

const readCalendars = `-- name: ReadCalendars :many
select path, sync_token, dto from calendar
`

func (q *Queries) ReadCalendars(ctx context.Context) ([]Calendar, error) {
	rows, err := q.db.QueryContext(ctx, readCalendars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(&i.Path, &i.SyncToken, &i.Dto); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readMetadata = `-- name: ReadMetadata :one
select version from metadata
where id = 1
`

func (q *Queries) ReadMetadata(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, readMetadata)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const updateCalSyncToken = `-- name: UpdateCalSyncToken :exec
insert into calendar (path, sync_token)
values (?, ?)
on conflict (path) do update set
	sync_token = excluded.sync_token
`

type UpdateCalSyncTokenParams struct {
	Path      string
	SyncToken sql.NullString
}

func (q *Queries) UpdateCalSyncToken(ctx context.Context, arg UpdateCalSyncTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateCalSyncToken, arg.Path, arg.SyncToken)
	return err
}
